### ISSUE TITLE
Android app.

### ISSUE THREAD

**Issue by ingnelson** [mstephen77/dns-doh-proxy#1]
Hello sir.
Can you create a Android app ?
I would like to use it to bypass my Firewall.
Thank.

**Comment by mstephen77** [comment]
This project aims to create a DNS server using Python Programming Language. As of now, it is near-impossible to set up a server in a non-rooted / un-jailbroken smartphone devices. Instead, you may try:
- Buying a microcontroller for a local DNS server using several open-sourced programs, or
- Use free VPNs from publicly well-known brands
